[colors.primary]
background = "#0e201d"
foreground = "#c2c7c6"

[colors.cursor]
text = "#0e201d"
cursor = "#c2c7c6"

[colors.vi_mode_cursor]
text = "#0e201d"
cursor = "#c2c7c6"

[colors.search.matches]
foreground = "#0e201d"
background = "#c2c7c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5d726e"
background = "#c2c7c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0e201d"
red = "#798666"
green = "#B69B2A"
yellow = "#9C925F"
blue = "#8D9374"
magenta = "#738F96"
cyan = "#99A695"
white = "#c2c7c6"

[colors.bright]
black = "#5d726e"
red = "#798666"
green = "#B69B2A"
yellow = "#9C925F"
blue = "#8D9374"
magenta = "#738F96"
cyan = "#99A695"
white = "#c2c7c6"

[colors.dim]
black = "#c2c7c6"
red = "#798666"
green = "#738F96"
yellow = "#9C925F"
blue = "#8D9374"
magenta = "#B69B2A"
cyan = "#99A695"
white = "#5d726e"

