#!/bin/bash
# Configuration
WALLPAPER_DIR="/home/isg32/pics/walls"
WAYBAR_CSS="/home/isg32/.config/waybar/colors-waybar.css"
STATE_FILE="/home/isg32/.config/hypr/wallpaper_index"

# --- Function to Clean Hex Codes ---
# Ensures that any remaining spaces, newlines, or carriage returns are removed.
clean_hex() {
    echo "$1" | tr -d '[:space:]\n\r'
}

# --- Error Checking ---
if [ ! -d "$WALLPAPER_DIR" ]; then
    echo "Error: Directory not found at $WALLPAPER_DIR"
    exit 1
fi

# --- Get sorted list of wallpapers ---
mapfile -t WALLPAPERS < <(find "$WALLPAPER_DIR" -type f | sort)

if [ ${#WALLPAPERS[@]} -eq 0 ]; then
    echo "Error: No files found in the directory."
    exit 1
fi

# --- Read current index or initialize ---
if [ -f "$STATE_FILE" ]; then
    CURRENT_INDEX=$(cat "$STATE_FILE")
else
    CURRENT_INDEX=0
fi

# --- Select wallpaper ---
SELECTED_WALLPAPER="${WALLPAPERS[$CURRENT_INDEX]}"

# --- Calculate next index (wrap around to 0) ---
NEXT_INDEX=$(( (CURRENT_INDEX + 1) % ${#WALLPAPERS[@]} ))

# --- Save next index for next execution ---
echo "$NEXT_INDEX" > "$STATE_FILE"

# --- Apply wallpaper ---
swww img "$SELECTED_WALLPAPER" && wal -i "$SELECTED_WALLPAPER"

# --- Color Palette Extraction with gowall ---
COLOR_PALETTE=$(/home/isg32/.config/hypr/scripts/gowall extract "$SELECTED_WALLPAPER" | head -n -1)

# Read the colors into an array and clean them immediately
i=0
COLORS=()
while IFS= read -r line; do
    COLORS[i]=$(clean_hex "$line")
    ((i++))
done <<< "$COLOR_PALETTE"

# --- Generate CSS Variables for Waybar ---
# Assign and clean core colors (with fallbacks)
COLOR_0=$(clean_hex "${COLORS[0]:-"#D1D1D1"}")
COLOR_1=$(clean_hex "${COLORS[1]:-"#A1A1A1"}")
COLOR_2=$(clean_hex "${COLORS[2]:-"#717171"}")
COLOR_3=$(clean_hex "${COLORS[3]:-"#414141"}")
COLOR_4=$(clean_hex "${COLORS[4]:-"#1A1A1A"}")
COLOR_5=$(clean_hex "${COLORS[5]:-"#050505"}")

# Define core theme colors
FG_COLOR=$COLOR_0
BG_COLOR=$COLOR_4

COLOR_BLOCK="/* Generated by wallpaper.sh and gowall on $(date) */
/* Core Theme Colors for Waybar CSS */
@define-color foreground ${FG_COLOR};
@define-color background ${BG_COLOR};
/* gowall Palette Colors (0-5) */
@define-color color0 ${COLOR_0};
@define-color color1 ${COLOR_1};
@define-color color2 ${COLOR_2};
@define-color color3 ${COLOR_3};
@define-color color4 ${COLOR_4};
@define-color color5 ${COLOR_5};
"

# Write the new color block to the file
echo -e "$COLOR_BLOCK" > "$WAYBAR_CSS"

echo "Wallpaper set (${CURRENT_INDEX}/${#WALLPAPERS[@]}): $SELECTED_WALLPAPER"
echo "Color palette written to: $WAYBAR_CSS"
