#!/bin/bash

# --- Configuration ---
WALLPAPER_DIR="/home/isg32/pics/walls"
WAYBAR_CSS="/home/isg32/.config/waybar/colors-waybar.css"
STATE_FILE="/home/isg32/.config/hypr/wallpaper_index"
GOWALL_SCRIPT="/home/isg32/.config/hypr/scripts/gowall"

# --- Helper: Clean Hex ---
clean_hex() {
    echo "$1" | tr -d '[:space:]\n\r'
}

# --- Ensure swww is running ---
if ! swww query &> /dev/null; then
    swww-daemon --format xrgb &
    sleep 0.5
fi

# --- Get sorted list of wallpapers ---
mapfile -t WALLPAPERS < <(find "$WALLPAPER_DIR" -type f | sort)

if [ ${#WALLPAPERS[@]} -eq 0 ]; then
    echo "Error: No files found in $WALLPAPER_DIR"
    exit 1
fi

# --- Logic: Determine Index ---
if [ -f "$STATE_FILE" ]; then
    CURRENT_INDEX=$(cat "$STATE_FILE")
else
    CURRENT_INDEX=0
fi

# Reset index if out of bounds
if [ "$CURRENT_INDEX" -ge "${#WALLPAPERS[@]}" ] || [ "$CURRENT_INDEX" -lt 0 ]; then
    CURRENT_INDEX=0
fi

# --- Select and Apply Wallpaper ---
SELECTED_WALLPAPER="${WALLPAPERS[$CURRENT_INDEX]}"

echo "Applying ($CURRENT_INDEX): $SELECTED_WALLPAPER"
swww img "$SELECTED_WALLPAPER" --transition-type grow --transition-pos 0.5,0.5 --transition-step 90
wal -i "$SELECTED_WALLPAPER" -n -q

# --- Calculate Next Index and Save ---
NEXT_INDEX=$(( (CURRENT_INDEX + 1) % ${#WALLPAPERS[@]} ))
echo "$NEXT_INDEX" > "$STATE_FILE"

# --- Update Waybar Colors ---
if [ -f "$GOWALL_SCRIPT" ]; then
    COLOR_PALETTE=$("$GOWALL_SCRIPT" extract "$SELECTED_WALLPAPER" | head -n -1)

    i=0
    COLORS=()
    while IFS= read -r line; do
        COLORS[i]=$(clean_hex "$line")
        ((i++))
    done <<< "$COLOR_PALETTE"

    # Assign palette colors (we still calculate these for accents)
    COLOR_0=$(clean_hex "${COLORS[0]:-"#D1D1D1"}")
    COLOR_1=$(clean_hex "${COLORS[1]:-"#A1A1A1"}")
    COLOR_2=$(clean_hex "${COLORS[2]:-"#717171"}")
    COLOR_3=$(clean_hex "${COLORS[3]:-"#414141"}")
    COLOR_4=$(clean_hex "${COLORS[4]:-"#1A1A1A"}")
    COLOR_5=$(clean_hex "${COLORS[5]:-"#050505"}")

    # --- FORCED OVERRIDES ---
    # Setting Background to Black and Text to White
    FG_COLOR="#FFFFFF"
    BG_COLOR="#000000"

    COLOR_BLOCK="/* Generated by wallpaper_manager.sh on $(date) */
/* Forced High Contrast Theme */
@define-color foreground ${FG_COLOR};
@define-color background ${BG_COLOR};

/* gowall Palette Colors (Available for accents) */
@define-color color0 ${COLOR_0};
@define-color color1 ${COLOR_1};
@define-color color2 ${COLOR_2};
@define-color color3 ${COLOR_3};
@define-color color4 ${COLOR_4};
@define-color color5 ${COLOR_5};
"

    # Write to file
    echo -e "$COLOR_BLOCK" > "$WAYBAR_CSS"

    # Reload Waybar to see changes immediately
    pkill -SIGUSR2 waybar
fi
