#!/bin/bash

# Configuration
WALLPAPER_DIR="/home/isg32/pics/walls"
WAYBAR_CSS="/home/isg32/.config/waybar/colors-waybar.css"

# --- Function to Clean Hex Codes ---
# Ensures that any remaining spaces, newlines, or carriage returns are removed.
clean_hex() {
    # Remove all spaces, newlines, and carriage returns from the variable
    echo "$1" | tr -d '[:space:]\n\r'
}

# --- Error Checking and Wallpaper Selection ---
if [ ! -d "$WALLPAPER_DIR" ]; then
    echo "Error: Directory not found at $WALLPAPER_DIR"
    exit 1
fi
RANDOM_WALLPAPER=$(find "$WALLPAPER_DIR" -type f | shuf -n 1 | xargs)
if [ -z "$RANDOM_WALLPAPER" ]; then
    echo "Error: No files found in the directory."
    exit 1
fi
swww img "$RANDOM_WALLPAPER" && wal -i "$RANDOM_WALLPAPER"

# --- Color Palette Extraction with gowall ---
COLOR_PALETTE=$(/home/isg32/.config/hypr/scripts/gowall extract "$RANDOM_WALLPAPER" | head -n -1)

# Read the colors into an array and clean them immediately
i=0
COLORS=()
while IFS= read -r line; do
    COLORS[i]=$(clean_hex "$line")
    ((i++))
done <<< "$COLOR_PALETTE"

# --- Generate CSS Variables for Waybar ---

# Assign and clean core colors (with fallbacks)
COLOR_0=$(clean_hex "${COLORS[0]:-"#D1D1D1"}")
COLOR_1=$(clean_hex "${COLORS[1]:-"#A1A1A1"}")
COLOR_2=$(clean_hex "${COLORS[2]:-"#717171"}")
COLOR_3=$(clean_hex "${COLORS[3]:-"#414141"}")
COLOR_4=$(clean_hex "${COLORS[4]:-"#1A1A1A"}")
COLOR_5=$(clean_hex "${COLORS[5]:-"#050505"}")

# Define core theme colors
FG_COLOR=$COLOR_0
BG_COLOR=$COLOR_4

# 🎨 FIX: REMOVE 8-DIGIT HEX DEFINITIONS. We only define the 6-digit hex codes.

COLOR_BLOCK="/* Generated by wallpaper.sh and gowall on $(date) */

/* Core Theme Colors for Waybar CSS */
@define-color foreground ${FG_COLOR};
@define-color background ${BG_COLOR};

/* gowall Palette Colors (0-5) */
@define-color color0 ${COLOR_0};
@define-color color1 ${COLOR_1};
@define-color color2 ${COLOR_2};
@define-color color3 ${COLOR_3};
@define-color color4 ${COLOR_4};
@define-color color5 ${COLOR_5};

"

# Write the new color block to the file
echo -e "$COLOR_BLOCK" > "$WAYBAR_CSS"

echo "New wallpaper set: $RANDOM_WALLPAPER"
echo "Color palette written to: $WAYBAR_CSS"
